---
title: "Untitled"
author: "Sofia"
date: "11/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing file and libraries

First we will read the file, import the tidyverse library to manipulate the dataset and reticulate to be able to play with python as well. First we are going to drop the columns X and X.1

```{r}

library(tidyverse) 
library(reticulate) 

use_python("/usr/bin/python3", required = F)

# do not touch these settings
Sys.which("python")
Sys.getenv("DISPLAY") 

matplotlib <- import("matplotlib", convert = TRUE)
matplotlib$use("Agg")


install.packages("gridExtra")
library("gridExtra")

```


```{r}

#First we read the file

data <- read.csv("ENB2012_data (2).csv")

#When the file is loaded, two empty columns appear, which we now drop from the dataset. Then we make sure that there are no missing values in the data.

data %>% select(-X, -X.1) %>% na.omit() -> data

#Here we are re-labeling the column names to make them more intuitive

data <- data %>% select(relative_compactness = 'X1', surface_area = 'X2', wall_area = 'X3', roof_area = 'X4', overall_height = 'X5', orientation = 'X6', glazing_area = 'X7', glazing_area_distribution = 'X8', heating_load = 'Y1', cooling_load = 'Y2')

#Here we are converting glazing are distribution (which is categorical with no natural order) into several dummy variables

data1 <- data %>% mutate(glazing_area_distribution1 = ifelse(glazing_area_distribution == 1,1,0), glazing_area_distribution2 = ifelse(glazing_area_distribution == 2,1,0),glazing_area_distribution3 = ifelse(glazing_area_distribution == 3,1,0), glazing_area_distribution4 = ifelse(glazing_area_distribution == 4,1,0), glazing_area_distribution5 = ifelse(glazing_area_distribution == 4,1,0))

#We do the same for orientation, which is also a categorical variable

data1 <- data1 %>% mutate(orientation2 = ifelse(orientation == 2,1,0), orientation3 = ifelse(orientation == 3,1,0), orientation4 = ifelse(orientation == 4,1,0), orientation5 = ifelse(orientation == 5,1,0))

#Finally, we drop the original orientation and glazing area distribution variables

data1 <- data1 %>% select(-orientation, -glazing_area_distribution)

#We decided not to scale the data since we will be using regression models that don't rely on distances, therefore normalizing it will add no value
```


```{r}

#We first plot the response variables, which are heating and cooling load. 
ggplot(data, aes(x= heating_load)) + geom_histogram(aes(y = ..density..))+ geom_density()
ggplot(data, aes(x= cooling_load)) + geom_histogram(aes(y = ..density..))+ geom_density()

#We can see that both variables follow a bimodal distribution, and they have basically the same distribution but the cooling load appears to be shifted to the left

plot1 <- ggplot(data, aes(x=as.factor(relative_compactness), y=heating_load)) + geom_violin(trim=FALSE, color = "red") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "relative compactness", y = "heating load")
plot2 <- ggplot(data, aes(x=as.factor(surface_area), y=heating_load)) + geom_violin(trim=FALSE, color = "orange") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "surface area", y = "heating load")
plot3 <- ggplot(data, aes(x=as.factor(wall_area ), y=heating_load)) + geom_violin(trim=FALSE, color = "yellow") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "wall area ", y = "heating load")
plot4 <- ggplot(data, aes(x=as.factor(roof_area), y=heating_load)) + geom_violin(trim=FALSE, color = "green") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "roof area", y = "heating load")
plot5 <- ggplot(data, aes(x=as.factor(overall_height), y=heating_load)) + geom_violin(trim=FALSE, color = "blue") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "overall height", y = "heating load")
plot6 <- ggplot(data, aes(x=as.factor(orientation), y=heating_load)) + geom_violin(trim=FALSE, color = "pink") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "orientation", y = "heating load")
plot7 <- ggplot(data, aes(x=as.factor(glazing_area), y=heating_load)) + geom_violin(trim=FALSE, color = "violet") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "glazing area", y = "heating load")
plot8 <- ggplot(data, aes(x=as.factor(glazing_area_distribution), y=heating_load)) + geom_violin(trim=FALSE, color = "black") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "glazing area distribution", y = "heating load")

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, ncol=4)

plot11 <- ggplot(data, aes(x=as.factor(relative_compactness), y=cooling_load)) + geom_violin(trim=FALSE, color = "red") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "relative compactness", y = "cooling load")
plot22 <- ggplot(data, aes(x=as.factor(surface_area), y=cooling_load)) + geom_violin(trim=FALSE, color = "orange") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "surface area", y = "cooling load")
plot33 <- ggplot(data, aes(x=as.factor(wall_area ), y=cooling_load)) + geom_violin(trim=FALSE, color = "yellow") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "wall area ", y = "cooling load")
plot44 <- ggplot(data, aes(x=as.factor(roof_area), y=cooling_load)) + geom_violin(trim=FALSE, color = "green") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "roof area", y = "cooling load")
plot55 <- ggplot(data, aes(x=as.factor(overall_height), y=cooling_load)) + geom_violin(trim=FALSE, color = "blue") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "overall height", y = "cooling load")
plot66 <- ggplot(data, aes(x=as.factor(orientation), y=cooling_load)) + geom_violin(trim=FALSE, color = "pink") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "orientation", y = "cooling_load")
plot77 <- ggplot(data, aes(x=as.factor(glazing_area), y=cooling_load)) + geom_violin(trim=FALSE, color = "violet") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "glazing area", y = "cooling load")
plot88 <- ggplot(data, aes(x=as.factor(glazing_area_distribution), y=cooling_load)) + geom_violin(trim=FALSE, color = "black") + geom_boxplot(width=0.1) + theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(x = "glazing area distribution", y = "cooling load")
grid.arrange(plot11, plot22, plot33, plot44, plot55, plot66, plot77, plot88, ncol=4) 

#From the graphs we can observe that the heating load seems to follow a step function when analyzed against relative compactness and surface area. For relative compactness there seems to be a threshold (of around 0.74), that when surpassed, triggers the heating load to increase. For the surface area, we can infer that when a threshold of around 662 is surpassed, the heating load diminishes. 

#On the other hand, when analyzing heating load against wall area we can observe a slightly positive trend, and when analyzing it against roof area we can evidence what resembles a negative quadratic function. However, none of these trends seem to be very strong so that we can draw conclusions, probably more values would need to be included to be able to do this. 

#Overall height seems to have a great impact on the response variable. A higher height seems to be related with a high heating load. 

#Finally, orientation, glazing area and glazing area distribution seem to have little or no effect on the heating load. 

#The same conclusions can be applied to the cooling load. 

```
```{r}

#We now do a correlation matrix to understand the relationship between the variables analyzed. For this analysis we only included the numerical variables

cormat <- data1  %>% select(-glazing_area_distribution1, -glazing_area_distribution2, -glazing_area_distribution3, -glazing_area_distribution4, -glazing_area_distribution5, -orientation2, -orientation3, -orientation4, -orientation5) %>% cor() %>% as.data.frame %>% rownames_to_column("var1")
tidycor <- cormat %>% pivot_longer(-1, names_to = "var2", values_to = "correlation")

#We establish factor levels for var1 and var2 just so that the plot puts heating and cooling load at the end of the correlation matrix

tidycor %>% mutate(var1 = fct_relevel(var1, 
            "relative_compactness", "surface_area", "wall_area", 
            "roof_area", "overall_height", "glazing_area", 
            "heating_load", "cooling_load")) %>% mutate(var2 = fct_relevel(var2, 
            "relative_compactness", "surface_area", "wall_area", 
            "roof_area", "overall_height", "glazing_area", 
            "heating_load", "cooling_load")) %>% ggplot(aes(var1, var2, fill=correlation)) + 
  geom_tile() + 
  scale_fill_gradient2(low="red", mid="white", high = "blue") +
  geom_text(aes(label=round(correlation,2)),color = "black", size = 3)+ #overlays correlation values
  theme(axis.text.x = element_text(angle = 90)) + #flips the x-axis labels
  coord_fixed() +
  labs(x = "variable 1", y = "variable 2")

#We can draw several conclusions from the correlation matrix. 

# First, the variables that seem to be highly positively correlated to heating and cooling load are overall height, relative compactness. On the other hand, roof area and surface are seem to be highly negatively correlated to them.

#The correlation between cooling and heating load is of 98%, which supports our hypothesis obtained above that the distribution of the response variables seems to be practically identical. 

#Finally, there is a high correlation between all numerical explanatory variables except for wall area, which might suggest that the setup of the experiment could be improved.


```

```{r}
#We now create a data frame that contains all the X variables and one for each response variable
data1 %>% select (relative_compactness, surface_area, wall_area, roof_area, overall_height, glazing_area, glazing_area_distribution1, glazing_area_distribution2, glazing_area_distribution3, glazing_area_distribution4, glazing_area_distribution5, orientation2, orientation3, orientation4, orientation5) -> X
data %>% select (heating_load) -> heating_load
data %>% select (cooling_load) -> cooling_load
```
## Modelling

```{python}

#We import all the libraries necessary for the analysis

import numpy as np
import matplotlib.pylab as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split

#We divide the data into training and testing samples

X_train, X_test, heating_load_train, heating_load_test = train_test_split(r.X, r.heating_load, random_state=0)

#We fit the training data with the linear regression model, then predict the y values using the x testing data and finally calculate the out of sample (or testing) MSE

reg1 = linear_model.LinearRegression()
reg1.fit(X_train, heating_load_train)
y_pred1_reg = reg1.predict(X_test)
mse_1_reg = np.mean((heating_load_test - y_pred1_reg)**2)

figure = plt.figure(figsize=(15, 11))

#subplot for r1 regression
ax = plt.subplot(1,2,1)
plt.title('Linear regression heating load')
plt.xlabel('Actual values heating load', size=12)
plt.ylabel('Predicted heating load', size=12)
plt.plot(heating_load_test,y_pred1_reg , '.b')


#Now we will do it to predict the cooling_load response variable

X_train2, X_test2, cooling_load_train2, cooling_load_test2 = train_test_split(r.X, r.cooling_load, random_state=0)

reg2 = linear_model.LinearRegression()
reg2.fit(X_train2, cooling_load_train2)
y_pred2_reg = reg2.predict(X_test2)
mse_2_reg = np.mean((cooling_load_test - y_pred2_reg)**2)


#subplot for r2 regression
ax = plt.subplot(1,2,2)
plt.title('Linear regression cooling load')
plt.xlabel('Actual values cooling load', size=12)
plt.ylabel('Predicted cooling load', size=12)
plt.plot(cooling_load_test,y_pred2_reg , '.b', color = 'red')




```
```{python}


```


Do it with SVM, knn, decision tree and random forests and say which one is better

```{python}
from sklearn.svm import SVR
figure2 = plt.figure(figsize=(15, 11))

X_train, X_test, heating_load_train, heating_load_test = train_test_split(r.X, r.heating_load, random_state=0)

SVR1 = SVR()
SVR1.fit(X_train, heating_load_train) 
y_pred1_svm = SVR1.predict(X_test)

y_pred1_svm = np.reshape(y_pred1_svm, (192,1))

mse_1_svr = np.mean((heating_load_test - y_pred1_svm)**2)

print(mse_1_svr)

#subplot for r1 regression
ax = plt.subplot(1,2,1)
plt.title('SVR heating load')
plt.xlabel('Actual values heating load', size=12)
plt.ylabel('Predicted heating load', size=12)
plt.plot(heating_load_test, y_pred1_svm  , '.b')


X_train, X_test, cooling_load_train, cooling_load_test = train_test_split(r.X, r.cooling_load, random_state=0)

SVR2 = SVR()
SVR2.fit(X_train, cooling_load_train) 
y_pred2_svm = SVR2.predict(X_test)

y_pred2_svm = np.reshape(y_pred2_svm, (192,1))

mse_2_svr = np.mean((cooling_load_test - y_pred2_svm)**2)

print(mse_2_svr)

#subplot for r2 regression
ax = plt.subplot(1,2,2)
plt.title('SVR cooling load')
plt.xlabel('Actual values cooling load', size=12)
plt.ylabel('Predicted cooling load', size=12)
plt.plot(cooling_load_test,y_pred2_svm , '.b', color = 'red')


```
```{python}
from sklearn.ensemble import RandomForestRegressor
figure3 = plt.figure(figsize=(15, 11))

X_train, X_test, heating_load_train, heating_load_test = train_test_split(r.X, r.heating_load, random_state=0)

randomforest = RandomForestRegressor()
randomforest.fit(X_train, heating_load_train.values.ravel())
y_pred1_randomf = randomforest.predict(X_test)

y_pred1_randomf = np.reshape(y_pred1_randomf, (192,1))

mse_1_randomf = np.mean((heating_load_test - y_pred1_randomf)**2)

print(mse_1_randomf)

ax = plt.subplot(1,2,1)
plt.title('Random forest heating_load')
plt.xlabel('Actual values heating_load', size=12)
plt.ylabel('Predicted heating_load', size=12)
plt.plot(heating_load_test, y_pred1_randomf , '.b')

#cooling_load

X_train, X_test, cooling_load_train, cooling_load_test = train_test_split(r.X, r.cooling_load, random_state=0)

randomforest = RandomForestRegressor()
randomforest.fit(X_train, cooling_load_train.values.ravel())
y_pred2_randomf = randomforest.predict(X_test)

y_pred2_randomf = np.reshape(y_pred2_randomf, (192,1))

mse_2_randomf = np.mean((cooling_load_test - y_pred2_randomf)**2)

print(mse_2_randomf)

ax = plt.subplot(1,2,2)
plt.title('Random forest heating_load')
plt.xlabel('Actual values heating_load', size=12)
plt.ylabel('Predicted heating_load', size=12)
plt.plot(cooling_load_test, y_pred2_randomf , '.b', color = 'red')
```





